{
 "title": "My dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Retention of Tranformed Messages",
   "type": "timeseries",
   "description": "Number of messages is shrinking or growing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (topic) (\n  (\n    kafka_server_broker_topic_metrics_messagesinpersec_rate{topic=\"http_logs_test\"} * 60\n    -\n    (\n      kafka_server_broker_topic_metrics_bytesoutpersec_rate{topic=\"http_logs_test\"} offset 1m\n      /\n      (\n        kafka_server_broker_topic_metrics_bytesinpersec_rate{topic=\"http_logs_test\"} offset 1m\n        /\n        clamp_min(kafka_server_broker_topic_metrics_messagesinpersec_rate{topic=\"http_logs_test\"} offset 1m, 1)\n      )\n    )\n  ) * 60\n)"
    }
   ]
  },
  {
   "title": "Bytes Sent Global",
   "type": "timeseries",
   "description": "Bytes are summed with minute granularity with global context. Source ID has not been grouped. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT raw_sum, m FROM bytes_per_min \nWHERE m >= now() - INTERVAL 1 DAY;"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "description": "Chart is counted with one minute granularity",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ts_minute, toString(status), sum(cnt) AS cnt\nFROM status_counts\nWHERE ts_minute >= now() - INTERVAL 1 DAY\nGROUP BY ts_minute, status\nORDER BY ts_minute, status;"
    }
   ]
  },
  {
   "title": "Bytes Sent Per Region",
   "type": "timeseries",
   "description": "Data grouped by resourceId",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfMinute(ts) AS time,\n  toString(sourceId) AS sourceId,  \n  sum(bytes) AS bytes    \nFROM bytes_per_min_localized\nWHERE ts >= toDateTime($__from / 1000)\n  AND ts <  toDateTime($__to   / 1000)\nGROUP BY time, sourceId\nORDER BY time, sourceId;"
    },
    {
     "rawSql": "SELECT\n  toStartOfMinute(ts) AS time,\n  sum(bytes) AS bytes\nFROM bytes_per_min_localized\nWHERE ts >= toDateTime($__from / 1000)\n  AND ts <  toDateTime($__to   / 1000)\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Cache States",
   "type": "timeseries",
   "description": "Counted with one minute granularity",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT ts_minute, toString(cacheStatus), sum(cnt) AS cnt\nFROM cache_counts\nWHERE ts_minute >= now() - INTERVAL 1 DAY\nGROUP BY ts_minute, cacheStatus\nORDER BY ts_minute, cacheStatus;"
    }
   ]
  },
  {
   "title": "Average Incoming Message Rate",
   "type": "timeseries",
   "description": "Per topic with 1 minute granularity",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (topic) (\n  avg_over_time(\n    floor(kafka_server_broker_topic_metrics_messagesinpersec_rate{\n      env=\"cluster-demo\",\n      instance=\"jmx-kafka:5556\",\n      job=\"kafka\",\n      service=\"kafka-broker\",\n      topic=~\"http_log|http_logs_test\"\n    } * 60)[1m:]\n  )\n)"
    }
   ]
  },
  {
   "title": "Message In Per Topic",
   "type": "timeseries",
   "description": "Aggregated to one minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "floor(\n  kafka_server_broker_topic_metrics_messagesinpersec_rate{\n    topic!~\"(__consumer_offsets)\",\n    topic!=\"\"\n  } * 60\n)"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } }
 ]
}